steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fis-api:$COMMIT_SHA', '.']
    dir: 'scripts'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fis-api:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fis-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fis-api:$COMMIT_SHA'
      - '--region'
      - 'asia-east1'  # Replace with your preferred region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      
images:
  - 'gcr.io/$PROJECT_ID/fis-api:$COMMIT_SHA' 